require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RushingStatsController do

  # This should return the minimal set of attributes required to create a valid
  # RushingStat. As you add validations to RushingStat, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RushingStatsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rushing_stats as @rushing_stats" do
      rushing_stat = RushingStat.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rushing_stats).should eq([rushing_stat])
    end
  end

  describe "GET show" do
    it "assigns the requested rushing_stat as @rushing_stat" do
      rushing_stat = RushingStat.create! valid_attributes
      get :show, {:id => rushing_stat.to_param}, valid_session
      assigns(:rushing_stat).should eq(rushing_stat)
    end
  end

  describe "GET new" do
    it "assigns a new rushing_stat as @rushing_stat" do
      get :new, {}, valid_session
      assigns(:rushing_stat).should be_a_new(RushingStat)
    end
  end

  describe "GET edit" do
    it "assigns the requested rushing_stat as @rushing_stat" do
      rushing_stat = RushingStat.create! valid_attributes
      get :edit, {:id => rushing_stat.to_param}, valid_session
      assigns(:rushing_stat).should eq(rushing_stat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RushingStat" do
        expect {
          post :create, {:rushing_stat => valid_attributes}, valid_session
        }.to change(RushingStat, :count).by(1)
      end

      it "assigns a newly created rushing_stat as @rushing_stat" do
        post :create, {:rushing_stat => valid_attributes}, valid_session
        assigns(:rushing_stat).should be_a(RushingStat)
        assigns(:rushing_stat).should be_persisted
      end

      it "redirects to the created rushing_stat" do
        post :create, {:rushing_stat => valid_attributes}, valid_session
        response.should redirect_to(RushingStat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rushing_stat as @rushing_stat" do
        # Trigger the behavior that occurs when invalid params are submitted
        RushingStat.any_instance.stub(:save).and_return(false)
        post :create, {:rushing_stat => {}}, valid_session
        assigns(:rushing_stat).should be_a_new(RushingStat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RushingStat.any_instance.stub(:save).and_return(false)
        post :create, {:rushing_stat => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rushing_stat" do
        rushing_stat = RushingStat.create! valid_attributes
        # Assuming there are no other rushing_stats in the database, this
        # specifies that the RushingStat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RushingStat.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => rushing_stat.to_param, :rushing_stat => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested rushing_stat as @rushing_stat" do
        rushing_stat = RushingStat.create! valid_attributes
        put :update, {:id => rushing_stat.to_param, :rushing_stat => valid_attributes}, valid_session
        assigns(:rushing_stat).should eq(rushing_stat)
      end

      it "redirects to the rushing_stat" do
        rushing_stat = RushingStat.create! valid_attributes
        put :update, {:id => rushing_stat.to_param, :rushing_stat => valid_attributes}, valid_session
        response.should redirect_to(rushing_stat)
      end
    end

    describe "with invalid params" do
      it "assigns the rushing_stat as @rushing_stat" do
        rushing_stat = RushingStat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RushingStat.any_instance.stub(:save).and_return(false)
        put :update, {:id => rushing_stat.to_param, :rushing_stat => {}}, valid_session
        assigns(:rushing_stat).should eq(rushing_stat)
      end

      it "re-renders the 'edit' template" do
        rushing_stat = RushingStat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RushingStat.any_instance.stub(:save).and_return(false)
        put :update, {:id => rushing_stat.to_param, :rushing_stat => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rushing_stat" do
      rushing_stat = RushingStat.create! valid_attributes
      expect {
        delete :destroy, {:id => rushing_stat.to_param}, valid_session
      }.to change(RushingStat, :count).by(-1)
    end

    it "redirects to the rushing_stats list" do
      rushing_stat = RushingStat.create! valid_attributes
      delete :destroy, {:id => rushing_stat.to_param}, valid_session
      response.should redirect_to(rushing_stats_url)
    end
  end

end
